// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjU1vx41EG_m2wDEmWfUAs0iAZY1q-a9o',
    appId: '1:357756625610:web:095ada2b0ed148fc810a33',
    messagingSenderId: '357756625610',
    projectId: 'lingo-breeze-ab322',
    authDomain: 'lingo-breeze-ab322.firebaseapp.com',
    storageBucket: 'lingo-breeze-ab322.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBLTdViyRC8XcENLmLpe8w1BThBpR9TAs',
    appId: '1:357756625610:android:1be2eec3ef3d3f66810a33',
    messagingSenderId: '357756625610',
    projectId: 'lingo-breeze-ab322',
    storageBucket: 'lingo-breeze-ab322.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIXCfZGKt_azrS6VZWtySHyp3L2g6WEi0',
    appId: '1:357756625610:ios:03e9341c8b9a74f5810a33',
    messagingSenderId: '357756625610',
    projectId: 'lingo-breeze-ab322',
    storageBucket: 'lingo-breeze-ab322.firebasestorage.app',
    iosBundleId: 'com.example.assignmentLingobreeze',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjU1vx41EG_m2wDEmWfUAs0iAZY1q-a9o',
    appId: '1:357756625610:web:06b12d55359f28c7810a33',
    messagingSenderId: '357756625610',
    projectId: 'lingo-breeze-ab322',
    authDomain: 'lingo-breeze-ab322.firebaseapp.com',
    storageBucket: 'lingo-breeze-ab322.firebasestorage.app',
  );
}
